# Reference: https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/default_callback.html
---
- name: "CALLBACK-BUILTIN-DEFAULT"
  hosts: "main"
  become: false
  gather_facts: false

  tasks:
    - name: "Current callback plugin"
      ansible.builtin.debug:
        msg: "DEFAULT_STDOUT_CALLBACK={{ lookup('ansible.builtin.config', 'DEFAULT_STDOUT_CALLBACK') }}"
...
