---
# Reference: https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/file_module.html
- name: "MODULE-BUILTIN-FILE"
  hosts: "main"
  become: false
  gather_facts: false

  tasks:
    - name: "Create file"
      ansible.builtin.file:
        path: "{{ lookup('env', 'DEV_PATH_PROF_TMP') + '/BUILTIN-FILE' }}"
        state: "touch"

    - name: "Set permissions"
      ansible.builtin.file:
        path: "{{ lookup('env', 'DEV_PATH_PROF_TMP') + '/BUILTIN-FILE' }}"
        state: "file"
        mode: "0600"

    - name: "Remove file"
      ansible.builtin.file:
        path: "{{ lookup('env', 'DEV_PATH_PROF_TMP') + '/BUILTIN-FILE' }}"
        state: "absent"

    - name: "Create directory"
      ansible.builtin.file:
        path: "{{ lookup('env', 'DEV_PATH_PROF_TMP') + '/BUILTIN-DIR' }}"
        state: "directory"

    - name: "Remove directory"
      ansible.builtin.file:
        path: "{{ lookup('env', 'DEV_PATH_PROF_TMP') + '/BUILTIN-DIR' }}"
        state: "absent"
...
