# Reference: https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/get_url_module.html
---
- name: "MODULE-BUILTIN-GETURL"
  hosts: "main"
  become: false
  gather_facts: false

  tasks:
    - name: "Get script from GitHub Repo and store locally"
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/automation64/installer64/main/src/bootstrap"
        dest: "/tmp/bootstrap"
        mode: '0755'
...
