---
# Reference: https://docs.ansible.com/projects/ansible/latest/plugins/lookup.html
- name: "PLUGINS-LOOKUP"
  hosts: "main"
  become: false
  gather_facts: false

  tasks:
    - name: "Show environment variable"
      ansible.builtin.debug:
        msg: "{{ lookup('env', 'DEV_PATH_PROF_TMP') }}"
...
